# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-11 08:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dinner', '0006_auto_20170509_0947'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomFood',
        ),
    ]
