# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-11 08:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dinner', '0007_delete_customfood'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomFood',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customUserName', models.TextField()),
                ('customFirstName', models.TextField()),
                ('customLastName', models.TextField()),
                ('firstFood', models.TextField()),
                ('garnish', models.TextField()),
                ('salad', models.TextField()),
                ('meatDish', models.TextField()),
                ('fruits', models.TextField()),
                ('complex', models.TextField()),
                ('customDate', models.DateField()),
                ('dinnerDate', models.DateField()),
                ('customPrice', models.FloatField()),
            ],
            options={
                'db_table': 'customFood',
            },
        ),
    ]
